### ISSUE TITLE
(Windows) lang.py 에서 UnicodeDecodeError

### ISSUE THREAD

**Issue by seungwonpark** [koistudy2/server#27]
python web.py를 해봤는데

>Traceback (most recent call last):
>	File "web.py", line 8, in (module)
>		import lang
>	File "lang.py", line 6, in (module)
>	lines = f.readlines()
>UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 52: illegal multibyte sequence

와 같은 에러메시지가 나옵니다. (파일의 경로명은 생략함) 이거 Windows 에서만 그런건가요...

**Comment by seungwonpark** [comment]
자문자답합니다. 간단한 문제였네요.

lang.py 에서
`with open('./lang.txt', encoding='UTF-8') as f:`
